ALTER TABLE users ADD COLUMN IF NOT EXISTS height_cm          INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS chronic_conditions TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bp_norm            TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS prescribed_meds    TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarded          BOOLEAN NOT NULL DEFAULT TRUE;
